### ISSUE TITLE
make a pull request ?

### ISSUE THREAD

**Issue by gordielachance** [void-spark/xbmc-somafm#2]
Hi, thanks for having updated the addon !
Could you do a pull request so it would be updated with your code in the "main" repo ?

**Comment by void-spark** [comment]
Great, I don't get notifications for new issues :)
What do you mean with the main repo? The oderik one?
I doubt that is still maintained :)

**Comment by void-spark** [comment]
Mind, seems someone else is putting more work in: https://github.com/Soma-FM-Kodi-Add-On
Looks like they're putting in more effort then me, so I'd recommend using that one now.
Seems they added it to the great Kodi repo too, which is even better :)
Closing this issue with that said :)
